#!/usr/local/bin/python3

from PIL import Image; import numpy as np
from math import log; from sys import argv

def group(L,q,pad):
	L += [pad]*((q-len(L)%q)%q)
	return [[P[i*q+k] for k in range(q)] for i in range(len(L)/q)]

if len(argv) != 4:
	print('Input the name of the file to encode as images.')
	print('Follow this by the desired root name of the output file.')
	print('Finally, follow with the desired height and width of the images.')
	print('Example:\tpython3 encodetoimg input.txt output.png 400 500')
	print('This will generate files with names output_01.png, output_02.png ...')
	exit(1)

ifn,ofn,H,W = argv[1],argv[2].split('.'),int(argv[3]),int(argv[4])

P = [ord(x) for x in open(ifn,'r').read()]
P = group(P,3,0)
P = group(P,W,[0,0,0])
img = group(P,H,[[0,0,0] for _ in range(W)])

ofn,ext = '.'.join(ofn[:-1])+'_',ofn[-1]
numWidth = int(log(len(img))/log(10))+1

for i in range(len(img)):
	num = str(i).rjust(numWidth,'0')
	Image.fromarray(np.uint8(img[i])).save(ofn + '_' + num + '.' + ext)

