#!/usr/local/bin/python3

from PIL import Image; import numpy as np; from sys import argv

if len(argv) != 2:
	print('Input the name of the file to encode as images.')
	print('Follow this by the desired root name of the output file.')
	print('Finally, follow with the desired height and width of the images.')
	print('Example:\tpython3 encodetoimg input.txt output.png 400 500')
	print('This will generate files with names output_01.png, output_02.png etc.')
	exit(1)
fileName = argv[1]






exit()

ar  = [[[x,0,0] for x in range(256)] for _ in range(80)]
ar += [[[0,x,0] for x in range(256)] for _ in range(80)]
ar += [[[0,0,x] for x in range(256)] for _ in range(80)]

Image.fromarray(np.uint8(ar)).save('asdf.png')





