#!/usr/local/bin/python3

from github import Github # pygithub.readthedocs.io/en/latest
from sys import argv
from os import system
from getpass import getpass
from os.path import expanduser
import json; import base64
from cryptography.fernet import Fernet
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC


salt = b'3.141592653589793'
maxbytes = 10*1000**2	# 10MB
maxfiles = 499			# 499*10MB = 4990MB = 4.99GB
maxrepos = 100			# 

maxbytes = 50000
maxfiles = 4



def getCipher(password):
	kdf = PBKDF2HMAC(algorithm=hashes.SHA256(),length=32,salt=salt,iterations=100000,backend=default_backend())
	return Fernet(base64.urlsafe_b64encode(kdf.derive(password.encode('utf-8'))))

def createRepo(token,repoName):
	try:
		print('creating new repo: ' + repoName, flush=True)
		g = Github(token)
		g.get_user().create_repo(repoName)
	except:
		print("ERROR: a file by this name already exists")
		exit(1)

def createFile(token,userName,repoName,fileName,fileContent,encrpytionPassword):
	C = getCipher(encrpytionPassword)
	try:
		print('creating new file: ' + fileName, flush=True)
		print('fileName=',fileName,'fileContent=',fileContent,flush=True,end='\n\n')
		g = Github(token)
		repo = g.get_repo(userName+"/"+repoName)
		if encrpytionPassword != '': fileContent = C.encrypt(fileContent)
		message = repo.create_file(fileName, "commit message", fileContent, branch="test")
		print('file creation message', message)
	except:
		print("ERROR: file not created")

def delRepo(token,userName,repoName):
	print('deleting the repo ' + repoName)
	curl = "curl -X DELETE -H 'Authorization: token "
	url = "' https://api.github.com/repos/"
	system(curl + token + url + userName + "/"+repoName)

def uploadZip(token,userName,encrpytionPassword,zipName):
	try: repos = open(zipName,'rb').read()
	except:
		print(zipName+' not found')
		exit(1)
	repos = [repos[k*maxbytes:(k+1)*maxbytes] for k in range(len(repos)//maxbytes+1)]
	repos = [repos[k*maxfiles:(k+1)*maxfiles] for k in range(len(repos)//maxfiles+1)]

	print('number of repos to upload: ' + str(len(repos)))
	print('number of files per repo: ' + str(len(repos[0])))

	for i in range(len(repos)):
		repoName = zipName+'_'+str(i).zfill(len(str(maxrepos)))
		createRepo(token,repoName)
		if i == 0:
			createFile(token,userName,repoName,'numRepos.txt',str(len(repos)),'')
		files = repos[i]
		createFile(token,userName,repoName,'numFiles.txt',str(len(files)),'')
		for j in range(len(files)):
			fileName = repoName+'file'+str(j).zfill(len(str(maxfiles)))
			createFile(token,userName,repoName,fileName,files[j],encrpytionPassword)

def gitrepoContent(repoName,encrpytionPassword):
	C = getCipher(encrpytionPassword)
	numFiles = int(open(repoName+'/numFiles.txt','r').read())
	content = b""
	for n in range(numFiles):
		fileName = repoName+'/'+repoName+'file'+str(n).zfill(len(str(maxfiles)))
		content += C.decrypt(open(fileName,'rb').read())
	return content

def downloadZip(token,username,password,encrpytionPassword,zipName):
	repoName = zipName + '_' + str(0).zfill(len(str(maxrepos)))
	url = 'git clone https://' + username + ':' + password
	print('downloading repo ' + repoName,flush=True)
	system('rm -rf ' + repoName)
	system(url + '@github.com/' + username + '/' + repoName + ' 2> /dev/null')
	numRepos = int(open(repoName+'/numRepos.txt','r').read())
	content = gitrepoContent(repoName,encrpytionPassword)
	system('rm -rf ' + repoName)
	for n in range(1,numRepos):
		repoName = zipName + '_' + str(n).zfill(len(str(maxrepos)))
		system(url + '@github.com/' + username + '/' + repoName + ' 2> /dev/null')
		content += gitrepoContent(repoName,encrpytionPassword)
		system('rm -rf ' + repoName)
	open(zipName,'wb').write(content)







if len(argv) != 3:
	print('ERROR: must provide 2 inputs: command filename')
	print("command is one of the following")
	print("upload,download,delete")
	exit(1)

command,zipName = argv[1],argv[2]

username = input('Enter your github username: ')
encrpytionPassword = getpass('Enter your encryption password: ')
keyfile = expanduser('~')+'/.gitstore.'+username+".json.enc"
try:
	content = open(keyfile,'rb').read()
except:
	print("The file "+keyfile+' was not found')
	print("Please input the following:")
	password = getpass('Enter your github password: ')
	token = getpass('Enter your github token: ')
	content = json.dumps({"password":password,'token':token}).encode('utf-8')
	open(keyfile,'wb').write(getCipher(encrpytionPassword).encrypt(content))
try:
	key = json.loads(getCipher(encrpytionPassword).decrypt(content))
	password,token = key['password'],key['token']
except:
	print("Either the file "+keyfile+' was corrupted')
	print("or your password was wrong")
	exit(1)



if command == 'upload':
	uploadZip(token,username,encrpytionPassword,zipName)
if command == 'download':
	downloadZip(token,username,password,encrpytionPassword,zipName)
if command == 'delete':
	delZip(token,username,password,zipName)








