#!/usr/local/bin/python3

from sys import version
print(version)
if version[0]!='3':
	print("python 2 is deprecated, please use python 3")
	exit()

import hashlib; import json; from getpass import getpass
from os import system, remove; from pyperclip import copy
from os.path import expanduser,realpath
from cryptography.fernet import Fernet
from random import randint as rand


fileName = "/".join(realpath(__file__).split('/')[:-1])+'/.passwordmanager.json.enc'
saltLen = 30


# utilities

def helpstr(state):
	if state == 'viewEntry': 
		print("p = copy password to clipboard")
		print("u = copy username to clipboard")
		print("w = copy website to clipboard")
		print("o = open website")
		print("e = edit entry")
		print("d = edit entry")
		print("press enter to return to search")

	if state == 'main':      return "FINISH THIS"


def Print(s):
	system('clear')
	print('*'*len(s)+'****\n'+'* '+s+' *\n'+'*'*len(s)+'****\n')


def hashfunc(s):
	hashGen = hashlib.sha512()
	hashGen.update(s.encode('utf-8'))
	return hashGen.hexdigest()


def randstr(l,s):
	nums = "1234567890"
	lets = "QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm"
	syms = "~!@#$%^&*()_+-={}|[]<>?,./"
	used = ""
	if 'n' in s: used += nums
	if 'l' in s: used += lets
	if 's' in s: used += syms
	if used == "": raise Exception('not enough character types chosen')
	return "".join([used[rand(0,len(used)-1)] for _ in range(l)])


def save(data,final=False):
	if final: start = ''
	else: start = ' '
	data['salt'] = randstr(saltLen,'snl')
	cipher = Fernet(hashfunc(data['password']+data['salt'])[:43]+'=')
	towrite = (start+data['salt']).encode('utf-8')+cipher.encrypt(json.dumps(data).encode('utf-8'))
	open(fileName,'wb').write(towrite)



# states

def exitState(empty):
	pass
	exit()

def load(empty):
	file,plainText,salt,data = "","","",{}
	try:
		file = open(fileName,'rb').read()
		if file[0] == 32:
			Print("WARNING")
			print("Your password manager apears to already be open")
			x = input("Press 'c' to continue or anything else to quit: ")
			if 'c' != x: return ('exitState',)
			file = file[1:]
		salt,file = file[:saltLen].decode(),file[saltLen:]
	except: return ('setup',)	# create new password manager
	Print("PASSWORD MANAGER")
	while True:
		password = getpass("\nEnter your master password here: ")
		cipher = Fernet(hashfunc(password+salt)[:43]+'=')
		try:
			plainText = cipher.decrypt(file)
			break
		except:
			print('\nWrong password, enter "x" to exit,')
			print('"d" to delete the password file and create new password manager,')
			x = getpass('or anything else to try again: ')
			if x == 'x': exit()
			elif x == 'd':
				print("Are you sure you want to delete the password file? This cannot be undone.")
				if getpass("Enter y if yes: ")=='y':
					remove(fileName)
					return ('setup',)
	try: data = json.loads(plainText)
	except:
		print('ERROR: the file has been corrupted')
		exit(1)
	save(data)
	return ('search',data)


def setup(empty):
	Print('WELCOME TO PASSWORD MANAGER!')
	while True:
		password = getpass('To start, first enter your master password: ')
		if password == getpass('Reenter your master password: '): break
		print("Your passwords don't match, try again")
	data = {'password':password,'salt':randstr(saltLen,'snl'),'entries':{}}
	save(data)
	print('You will now be taken to the main page, from there enter h for help')
	input('Enter anything to continue: ')
	return ('main',data)


def search(params):
	data,B = params[0],False
	Print('SEARCH')
	print('Press enter twice consecutively to return to main menu')
	print('or enter the name of an entry')
	while True:
		x = input(': ')
		if x=='':
			if B: return ('main',data)
			print('\n'.join([s for s in data['entries']]))
			B = True
		else:
			B = False
			if x[-1]==' ' and x.strip() in data['entries']: return ('viewEntry',data,x.strip())
			else:
				S = [s for s in data['entries'] if s[:len(x)]==x]
				if   len(S)==0 and len(x)!=0: print('No entries starting with "' + x + '" found')
				elif len(S)==0 and len(x)==0:
					print('Your password manager is empty!')
					print('Go to the main menue and enter "a" to add an entry.')
				elif len(S)==1: return ('viewEntry',data,S[0])
				else: print('\n'.join(S))


def main(params):
	data = params[0]
	Print('PASSWORD MANAGER')
	print('(Enter "h" for help)')
	while True:
		x = input(': ')
		if   x=='a': return ('addEntry',data)
		elif x=='':  return ('search',data)
		elif x=='c': return ('changeMasterPassword',data)
		elif x=='x':
			save(data,final=True)
			exit()
		elif x=='h': helpstr('main')
		else:        print('Unknown option "' + x + '"')


def changeMasterPassword(params):
	Print("CHANGE MASTER PASSWORD")
	data = params[0]
	while True:
		print("Press Enter to return to the main page")
		password = getpass('Enter new password: ')
		if password == '': break
		elif password!=getpass('Re-enter new password: '): print("passwords don't match, try again")
		else:
			data['password'] = password
			break
	save(data)
	input("The new password has been saved, press enter to continue: ")
	return ('main',data)


def addEntry(params):
	data = params[0]
	Print('ADD ENTRY')
	print("Provide the following: service name, username, website, notes, password")
	print("'notes' may be multilined, to stop writting to 'notes' press enter on an empty line")
	while True:
		service = input("\nEntry name: ").strip()
		if service in data['entries']: print('this entry already exists')
		elif service == '': print("the entry can't have an empty string for its name")
		else: break
	username = input("username: ")
	website = input("website: ")
	if website[:8]!='https://': website = 'https://' + website
	print("enter your notes below:")
	notes = ""

	while True:
		nextline = input()
		notes += nextline+'\n'
		if nextline == '': break
	
	print("\nTo generate a password, enter the desired length (at least 10, at most 99)")
	print("followed by some subset of the characters 'n','l','s'")
	print("Including n will generate a password with numbers")
	print("and similarly for 'l' and letters and 's' for symbols")
	print("For example, '30 ns' will result in a password")
	print("of length 30 with only numbers and symbols")
	print("If a number is not provided or not enough symbols are used")
	print("this setting will default to '30 nls'")
	x = input("To use a custom password, simply press enter: ")

	if x == '':
		while True:
			password = getpass("password: ")
			if password == getpass("reenter password: "): break
			print("passwords don't match, try again")
	else:
		l = 30
		try: l = int(x[:2])
		except: pass
		try: password = randstr(l,x)
		except: password = randstr(l,'snl')
	
	data['entries'][service] = {'username':username,'website':website,'notes':notes,'password':password}
	save(data)
	input('Your entry has been saved, press enter to continue: ')
	return ('main',data)


def viewEntry(params):
	data,serviceName = params
	entry = data['entries'][serviceName]
	Print(serviceName)
	print('(Enter "h" for help)\n')
	print('Username:\t'     , entry['username'])
	print('Website:\t'      , entry['website'])
	print('Notes:')
	print(entry['notes'])
	while True:
		x = input(': ')
		if   x=='p': copy(entry['password'])
		elif x=='u': copy(entry['username'])
		elif x=='w': copy(entry['website'])

		elif x=='o': system('open ' + entry['website'])
		elif x=='e': return ('editEntry',data,serviceName)
		elif x=='':  return ('search',data)
		elif x=='h': helpstr('viewEntry')
		elif x=='d': return ('deleteEntry',data,serviceName)
		else:        print('Unknown option "' + x + '"')


def deleteEntry(params):
	data,serviceName = params
	print("Are you sure you want to delete this entry?")
	i = input('If yes press "y", press anything else to exit: ')
	if i=='y':
		del data['entries'][serviceName]
		save(data)
	return ('search',data)


def editEntry(data,serviceName):
	params = data,serviceName
	# FINISH THIS
	print('This feature is not yet implimented, sorry :(')
	return ('search',data)




if __name__ == '__main__':
	state = ('load',)
	try:
		while True:
			if    state[0] == 'load':                   state = load(state[1:])
			elif  state[0] == 'exitState':              state = exitState(state[1:])
			elif  state[0] == 'search':                 state = search(state[1:])
			elif  state[0] == 'setup':                  state = setup(state[1:])
			elif  state[0] == 'viewEntry':              state = viewEntry(state[1:])
			elif  state[0] == 'addEntry':               state = addEntry(state[1:])
			elif  state[0] == 'editEntry':              state = editEntry(state[1:])
			elif  state[0] == 'deleteEntry':            state = deleteEntry(state[1:])
			elif  state[0] == 'main':                   state = main(state[1:])
			elif  state[0] == 'changeMasterPassword':   state = changeMasterPassword(state[1:])
			else: raise Exception('unknown state: "' +  state[0] + '"')
	except Exception as e:
		print("SOFTWARE ERROR\nPlease notify the developer")
		# raise e
		exit(1)

