#!/usr/local/bin/python3

'''
THINGS TO DO:
have a file that you save the browser to and functionality
to change the default browser
'''


from sys import argv
from os import system

browser = 'Firefox'
url = "open 'https://duckduckgo.com/?t=ffab&q="
system(url + '+'.join(argv[1:]) + "&ia=web' -a " + browser)







